project_id = "vdpeyaphtsbrhygupfbc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54323
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[inbound_email]
enabled = false
port = 54330
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54321
file_size_limit = "50MiB"
image_transformation_limit = "256MB"

[auth]
enabled = true
port = 54321
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[edge_runtime]
enabled = true
port = 54321
inspector_port = 8083

[functions.generate-workout]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.process-waitlists]
verify_jwt = false

[functions.dispatch-waitlist-promotion-events]
verify_jwt = false

[functions.get-member-email]
verify_jwt = false

[functions.send-test-reactivation-webhook]
verify_jwt = false

[functions.notify-course-invitation]
verify_jwt = false

[functions.check-member-inactivity]
verify_jwt = false

[functions.send-news-email]
verify_jwt = true